/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bCHRxdj8eN21PNzfM9AohB

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsjgaY4LQzArdv } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: JgaY4LQzArdv/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsjgaY4LQzArdv
});
